# Generated by Django 5.2.7 on 2025-10-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20251017_1512'),
        ('blog', '0021_auto_20251017_1518'),
    ]

    operations = [
    ]
