# Generated by Django 5.2.7 on 2025-10-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_merge_0020_auto_20251017_1512_0021_auto_20251017_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutUs',
        ),
    ]
